### ISSUE TITLE
works on vWii

### ISSUE THREAD

**Issue by pumpkintheproot** [MikeIsAStar/szsHaxx#2]
Tested this on real hardware, just thought I'd let you know that you can execute this on a real vWii, however not tested to the fullest extent because no SD card larger than 2GB

However, since this requires modifications to allow Wiiconnect24 to be enabled, this is therefore useless

**Comment by pumpkintheproot** [comment]
lower than*

**Comment by pumpkintheproot** [comment]
![Uploading vwii.jpg…]()

**Comment by pumpkintheproot** [comment]
![vwii](https://github.com/MikeIsAStar/szsHaxx/assets/149212571/9f067bdd-8c58-4fcd-b06b-fc73f1cb1147)

**Comment by datkat21** [comment]
tested a couple days ago it does work on vWii too

**Comment by MikeIsAStar** [comment]
This information is valuable to have in case a workaround is discovered in the future.
