### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by LNLenost** [MikeIsAStar/szsHaxx#3]
I would like to add italian language.

**Comment by MikeIsAStar** [comment]
Thank you for your interest in contributing.

The following slices of text will need to be translated:

```
Permission

By: MikeIsAStar

By clicking the 'Start' button,
you permit the execution of
arbitrary code on your console.
```

**Comment by LNLenost** [comment]
In which file?

**Comment by LNLenost** [comment]
> ```
> Permesso
> 
> Di: MikeIsAStar
> 
> Cliccando il pulsante "Inizia",
> permetti l'esecuzione di
> codice arbitrario sulla tua console.
> ```

**Comment by pumpkintheproot** [comment]
Here's a French translation by me:

`Autorisation

Par: MikeIsAStar

En cliquant sur le bouton 'Démarrer',
vous autorisez l'exécution de
code arbitraire sur votre console.`

**Comment by JohnP55** [comment]
> Here's a French translation by me:
> 
> ```
> Autorisation
> 
> Par: MikeIsAStar
> 
> En cliquant sur le bouton 'Démarrer',
> vous autorisez l'exécution de
> code arbitraire sur votre console.
> ```

I have a couple nitpicks on that French translation:

- The 'Start' button in the French translations of tournaments was labeled "Commencer", not "Démarrer".

- Why did you translate "Permission" as "Autorisation"? Permission is already a word in French.

- IMO, "Permettre" is better suited than "Autoriser" here. "Autoriser" feels more explicit vs agreeing to let arbitrary code execute.

**Comment by MikeIsAStar** [comment]
Italian and French translations have been added via commits [ff87f88](https://github.com/MikeIsAStar/szsHaxx/commit/ff87f88d018b33582292bda5907751591531bb7c) and [4ddd008](https://github.com/MikeIsAStar/szsHaxx/commit/4ddd00854113bd1fd9c55ba53eb72e868e4dd1c8), respectively.

**Comment by DDinghoya** [comment]
> Italian and French translations have been added via commits [ff87f88](https://github.com/MikeIsAStar/szsHaxx/commit/ff87f88d018b33582292bda5907751591531bb7c) and [4ddd008](https://github.com/MikeIsAStar/szsHaxx/commit/4ddd00854113bd1fd9c55ba53eb72e868e4dd1c8), respectively.

Is the translation of Korean still valid?

> ```
> 허용
> 
> 제작자: MikeIsAStar
> 
> '시작' 버튼을 클릭하면,
> 콘솔에서 임의의 코드 실행이
> 허용됩니다.
> ```

**Comment by MikeIsAStar** [comment]
> Is the translation of Korean still valid?

The current Korean translation reads as follows:

```
허가

만든 이: MikeIsAStar

'START' 버튼을 누를 시
콘솔에 임의 코드 실행을 허용합니다.
```

If you believe that your version of the translation is more accurate, I would be pleased to update the existing translation.

**Comment by LNLenost** [comment]
> Italian and French translations have been added via commits [ff87f88](https://github.com/MikeIsAStar/szsHaxx/commit/ff87f88d018b33582292bda5907751591531bb7c) and [4ddd008](https://github.com/MikeIsAStar/szsHaxx/commit/4ddd00854113bd1fd9c55ba53eb72e868e4dd1c8), respectively.

Thx :D
